// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addinguserpropinNP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinguserpropinNP));
        
        string IMigrationMetadata.Id
        {
            get { return "201808210355382_adding user prop in NP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
